services:
  - type: web
    name: car-dealership
    env: dotnet
    plan: free
    buildCommand: dotnet publish -c Release -o out
    startCommand: dotnet out/Car_Dealership.dll
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
