// <auto-generated />
using System;
using Car_Dealership.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Car_Dealership.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Car_Dealership.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessLevel")
                        .HasColumnType("int");

                    b.Property<int>("HorsePower")
                        .HasColumnType("int");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductionYear")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessLevel = 2,
                            HorsePower = 340,
                            Manufacturer = "Audi",
                            Model = "A7",
                            Price = 6000000m,
                            ProductionYear = 2022
                        },
                        new
                        {
                            Id = 2,
                            AccessLevel = 1,
                            HorsePower = 600,
                            Manufacturer = "Audi",
                            Model = "RS7",
                            Price = 18000000m,
                            ProductionYear = 2023
                        },
                        new
                        {
                            Id = 3,
                            AccessLevel = 1,
                            HorsePower = 620,
                            Manufacturer = "BMW",
                            Model = "M850i",
                            Price = 17000000m,
                            ProductionYear = 2021
                        },
                        new
                        {
                            Id = 4,
                            AccessLevel = 2,
                            HorsePower = 320,
                            Manufacturer = "BMW",
                            Model = "M340i",
                            Price = 4500000m,
                            ProductionYear = 2023
                        },
                        new
                        {
                            Id = 5,
                            AccessLevel = 3,
                            HorsePower = 350,
                            Manufacturer = "Porsche",
                            Model = "Cayman 4s",
                            Price = 4000000m,
                            ProductionYear = 2017
                        },
                        new
                        {
                            Id = 6,
                            AccessLevel = 1,
                            HorsePower = 490,
                            Manufacturer = "Mercedes-Benz",
                            Model = "S-Class",
                            Price = 10000000m,
                            ProductionYear = 2020
                        },
                        new
                        {
                            Id = 7,
                            AccessLevel = 1,
                            HorsePower = 1020,
                            Manufacturer = "Tesla",
                            Model = "Model S",
                            Price = 8000000m,
                            ProductionYear = 2023
                        },
                        new
                        {
                            Id = 8,
                            AccessLevel = 3,
                            HorsePower = 450,
                            Manufacturer = "Ford",
                            Model = "Mustang",
                            Price = 5500000m,
                            ProductionYear = 2022
                        },
                        new
                        {
                            Id = 9,
                            AccessLevel = 1,
                            HorsePower = 495,
                            Manufacturer = "Chevrolet",
                            Model = "Corvette",
                            Price = 7000000m,
                            ProductionYear = 2022
                        },
                        new
                        {
                            Id = 10,
                            AccessLevel = 2,
                            HorsePower = 335,
                            Manufacturer = "Toyota",
                            Model = "Supra",
                            Price = 4000000m,
                            ProductionYear = 2023
                        },
                        new
                        {
                            Id = 11,
                            AccessLevel = 1,
                            HorsePower = 565,
                            Manufacturer = "Nissan",
                            Model = "GT-R",
                            Price = 9000000m,
                            ProductionYear = 2020
                        },
                        new
                        {
                            Id = 12,
                            AccessLevel = 2,
                            HorsePower = 612,
                            Manufacturer = "Ferrari",
                            Model = "Roma",
                            Price = 24000000m,
                            ProductionYear = 2022
                        },
                        new
                        {
                            Id = 13,
                            AccessLevel = 1,
                            HorsePower = 640,
                            Manufacturer = "Lamborghini",
                            Model = "Huracán",
                            Price = 26000000m,
                            ProductionYear = 2022
                        },
                        new
                        {
                            Id = 14,
                            AccessLevel = 3,
                            HorsePower = 575,
                            Manufacturer = "Jaguar",
                            Model = "F-Type",
                            Price = 8000000m,
                            ProductionYear = 2023
                        },
                        new
                        {
                            Id = 15,
                            AccessLevel = 2,
                            HorsePower = 550,
                            Manufacturer = "Maserati",
                            Model = "GranTurismo",
                            Price = 12000000m,
                            ProductionYear = 2022
                        },
                        new
                        {
                            Id = 16,
                            AccessLevel = 1,
                            HorsePower = 503,
                            Manufacturer = "Aston Martin",
                            Model = "DB11",
                            Price = 19000000m,
                            ProductionYear = 2022
                        },
                        new
                        {
                            Id = 17,
                            AccessLevel = 1,
                            HorsePower = 1500,
                            Manufacturer = "Bugatti",
                            Model = "Chiron",
                            Price = 30000000m,
                            ProductionYear = 2023
                        },
                        new
                        {
                            Id = 18,
                            AccessLevel = 1,
                            HorsePower = 563,
                            Manufacturer = "Rolls-Royce",
                            Model = "Phantom",
                            Price = 28000000m,
                            ProductionYear = 2023
                        },
                        new
                        {
                            Id = 19,
                            AccessLevel = 1,
                            HorsePower = 626,
                            Manufacturer = "Bentley",
                            Model = "Continental GT",
                            Price = 25000000m,
                            ProductionYear = 2023
                        },
                        new
                        {
                            Id = 20,
                            AccessLevel = 1,
                            HorsePower = 710,
                            Manufacturer = "McLaren",
                            Model = "720S",
                            Price = 25000000m,
                            ProductionYear = 2023
                        });
                });

            modelBuilder.Entity("Car_Dealership.Models.Purchase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PurchasedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("UserId");

                    b.ToTable("Purchases");
                });

            modelBuilder.Entity("Car_Dealership.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<byte>("Rating")
                        .HasColumnType("tinyint");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("Car_Dealership.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessLevel")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessLevel = 1,
                            Password = "admin123",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            AccessLevel = 2,
                            Password = "manager123",
                            Username = "manager"
                        },
                        new
                        {
                            Id = 3,
                            AccessLevel = 3,
                            Password = "client123",
                            Username = "client"
                        });
                });

            modelBuilder.Entity("Car_Dealership.Models.Purchase", b =>
                {
                    b.HasOne("Car_Dealership.Models.Car", "Car")
                        .WithMany()
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Car_Dealership.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Car_Dealership.Models.Review", b =>
                {
                    b.HasOne("Car_Dealership.Models.Car", "Car")
                        .WithMany("Reviews")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Car_Dealership.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Car");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Car_Dealership.Models.Car", b =>
                {
                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
